config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'clients#index'
  resources :clients do
    resources :cars, only: %i[new create]
  end
  resources :cars, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :client
  validates :brand, presence: true
  validates :model, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :cars, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_client, only: %i[new create]

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.client = @client
    if @car.save
      redirect_to client_path(@client), notice: 'Your car was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to client_path(@car.client), status: :see_other, alert: 'Your car has been deleted'
  end

  private

  def set_client
    @client = Client.find(params[:client_id])
  end

  def car_params
    params.require(:car).permit(:brand, :model)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %I[show edit update destroy]
  def index
    @clients = Client.all
  end

  def show
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to client_path(@client), notice: 'The client was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to client_path(@client), notice: 'The client was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path, status: :see_other, alert: 'Your client has been deleted'
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/cars/new.html.erb
<br>

<body class="bg-success p-2 text-dark bg-opacity-10">
  <div class="container d-flex align-items-center justify-content-center max-w-50">
    <div class="card border border-3 border border-success mb-5 bg-body rounded">
      <div class="card-body">
        <h1 class="text-center">New car</h1>
        <%= simple_form_for [@client, @car] do |form| %>
          <%= form.input :brand %>
          <%= form.input :model %>
          <%= form.button :submit, "Add car", class: "btn btn-primary" %>
        <% end %>
        <br>
      </div>
    </div>
  </div>
</body>

app/views/clients/_form.html.erb
<br>

<body class="bg-success p-2 text-dark bg-opacity-10">
  <div class="container d-flex align-items-center justify-content-center max-w-50">
    <div class="card border border-3 border border-success mb-5 bg-body rounded">
      <div class="card-body">
        <h1 class="text-center">Client</h1>
        <br>
        <%= simple_form_for(@client, html: { class: 'mx-auto' }) do |f| %>
          <%= f.input :first_name, class: "border border-success" %>
          <%= f.input :last_name, class: "border border-success" %>
          <div class="d-grid gap-2">
            <%= f.submit class: "btn btn-success opacity-90" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/clients/edit.html.erb
<%= render "form", client: @client %>

app/views/clients/index.html.erb
<br>
<div class="container-sm ">
  <div class="border border-secondary border border-2 bg-success p-2 text-white bg-opacity-85">
    <div class="text-center p-3 mb-2">
      <h1>Our Clients</h1>
    </div>
  </div>
  <table class=" table table-striped table-hover text-center border border-secondary bg-success p-2 text-dark bg-opacity-10 ">
    <thead class=" bg-success p-2 text-success bg-opacity-25 ">
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody >
      <% @clients.each do |client| %>
        <tr>
          <td><%=client.first_name %></td>
          <td><%=client.last_name %></td>
          <div>
            <td class="link-success" ><%= link_to "Show", client, class: "link-success" %></td>
            <td><%= link_to "Delete",client_path(client.id),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "link-success"%></td>
          </div>

        </tr>
      <% end %>
    </tbody>
  </table>
  <p><%= link_to("Add a new client ", new_client_path, class: "btn btn-success opacity-90" ) %></p>
</div>

app/views/clients/new.html.erb
<%= render "form", client: @client %>

app/views/clients/show.html.erb
<br>
<body class="bg-success p-2 text-dark bg-opacity-10">
  <div class="container d-flex align-items-center justify-content-center max-w-50 -sm">
    <div class="card mb-3 card border-success mb-3 border border-3 " style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="https://img1.freepng.es/20180809/qvb/kisspng-delta-computers-rentals-clip-art-computer-icons-photo-icons-matt-symbol-png-image-picpng-5b6ce7aa28da27.9546927915338638501673.jpg" class="img-fluid rounded-start" alt="..." width= 600px>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= @client.first_name.concat(" #{@client.last_name}") %></h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
            <div>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
          </p>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-between">
      <%= link_to("Back to all Clients", clients_path, class: "btn btn-success opacity-90") %>
      <%= link_to("Edit", edit_client_path, class: "btn btn-success opacity-90") %>
      <%= link_to "Add car", new_client_car_path(client_id: @client.id), class: "btn btn-success opacity-90" %>
    </div>
    </div>
  </div>



  <div class="container d-flex justify-content-center">

    <% @client.cars.each do |car| %>
    <div class="card mb-3 border-success mb-3 border border-3" style="max-width: 10rem; display: inline-block; margin-right: 30px;">
      <img src="https://cdn.shopify.com/s/files/1/0518/0309/5239/products/lamborghini-veneno-remote-controlled-car-orange-852_800x.jpg?v=1677109651" class="card-img-top" alt="Car Image">
      <div class="card-body">
        <h5 class="card-title"><%= car.brand %></h5>
        <p class="card-text"><strong>Model:</strong> <%= car.model %></p>
        <%= link_to "Delete", car_path(car),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
      </div>
    </div>
    <% end %>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clients</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# bootstrap %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="container mt-5">
      <%= render "shared/navbar" %>
      <%= render "shared/alerts" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">

        <li class="nav-item">
          <p class="navbar-text float-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.|
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link"  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
              <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
            <% end %>
          </p>
        </li>
        <br>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>